name: Crawl Gold Price PNJ Data

on:
  schedule:
    #- cron: '0 4,9 * * *'  # Chạy vào 10h sáng (03 UTC) và 10h tối (15 UTC) theo giờ Việt Nam (GMT+7)
    - cron: '* * * * *'  # Chạy mỗi phút
  workflow_dispatch:  # Allow manual trigger

    


jobs:
  crawl-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}  # Token for push permission
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium
        
      - name: Run crawler
        run: python crawl_goldprices.py
      
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add result/*
          git diff --staged --quiet || git commit -m "Update gold price data [skip ci]"
          git push origin main
